version: '3'

services:
  nginx:
    image: linuxserver/letsencrypt:latest
    container_name: prod_bouncer.nginx
    ports:
      - '80'
      - '443'
    volumes:
      - ./:/var/www/bot
      - ./nginx.conf:/config/default.conf
    depends_on:
      - php
    environment:
      URL: dzmitry.xyz
      VALIDATION: http
      EMAIL: dmitry.lobanow@gmail.com

  php:
    build: Dockerfile-prod
    container_name: prod_bouncer.php
    volumes:
      - ./:/var/www/bot
