version: '3'

services:
  nginx:
    image: nginx:1.15
    container_name: prod.nginx
    ports:
      - 80:80
    volumes:
      - ./:/var/www/bot
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: Dockerfile-prod
    container_name: prod.php
    volumes:
      - ./:/var/www/bot

networks:
  default:
    external:
      name: webproxy
