version: '3'

services:
  nginx:
    restart: always
    image: dmitrylobanow/bouncer_nginx
    container_name: prod.nginx
    depends_on:
      - php

  php:
    restart: always
    image: dmitrylobanow/bouncer_php
    container_name: prod.php
    env_file:
      - .env
    volumes:
      - ./database.sqlite:/var/www/bot/storage/database.sqlite
      - ./logs:/var/www/bot/storage/logs

networks:
  default:
    external:
      name: webproxy
