FROM php:7.2-fpm

WORKDIR /var/www/bot

RUN apt-get update
RUN apt-get install -y --no-install-recommends \
    zlib1g-dev \
    git \
    gnupg \
    apt-transport-https \
    zip \
    unzip \
    cron

RUN docker-php-ext-install zip

# Cron
RUN printf "* * * * * cd /var/www/bot && /usr/local/bin/php artisan schedule:run >> /var/www/bot/storage/logs/cron.log 2>&1\n" >> /etc/cron.d/scheduler-cron
RUN chmod 0644 /etc/cron.d/scheduler-cron
RUN crontab /etc/cron.d/scheduler-cron
RUN touch /var/log/cron.log
# End

ENV APP_ENV = prod

COPY . /var/www/bot
COPY .env.example .env

# Change permissions
RUN chmod -R 0777 bootstrap/cache
RUN chmod -R 0777 storage

# Install dependencies
RUN php composer.phar install --no-ansi --no-dev --no-interaction --no-progress --optimize-autoloader

# Generate important key
RUN php artisan key:generate

CMD cron && php-fpm
